#pragma once
#define SCREEN_WIDTH 900
#define SCREEN_HEIGHT 900

#define STATE_MENU 0
#define STATE_GAME 3
#define STATE_GAME_MULTIPLAYER_OFFLINE 5
#define STATE_PAUSE 7
#define STATE_PLAYAGAIN 8
#define STATE_WIN 9
#define STATE_LOSE 10
#define STATE_REMIS 11
#define STATE_SETTINGS 12
#define STATE_RULES 13
#define STATE_SYMULATION_RESULT 14
#define STATE_SIMULATE 15

#define KRZYZYK 2
#define KOLKO 1
#define PUSTE_POLE 0

#define MUSIC_STATE_LOUDLY 1
#define MUSIC_STATE_QUIETLY 0

static int STATE;